11160-11161-fix(sortSettings): fix styles
Asdevtest/amazon-frontend pull request #1004
Opened 2024-11-07 06:27 UTC by tamashi22

2024-11-07 06:53 UTC, MrScotch679 approved these changes

2024-11-07 06:54 UTC, MrScotch679 requested changes

2024-11-07 06:54 UTC, MrScotch679 commented on src/ui/components/data-grid/data-grid-custom-components/sort-settings/select-sort-settings/select-sort-settings.tsx
> +        <CustomButton onClick={onToggleSelect}>{selectedItemName}</CustomButton>
Передай стили & .ant-btn через стили кнопки

2024-11-07 06:59 UTC, oltree approved these changes

2024-11-08 05:15 UTC, oltree approved these changes

2024-11-08 06:24 UTC, MrScotch679 approved these changes

2024-11-08 06:24 UTC, merged