10857-fix(clientMyRequest): fix column
Asdevtest/amazon-frontend pull request #760
Opened 2024-10-01 09:19 UTC by tamashi22

2024-10-01 13:54 UTC, oltree approved these changes

2024-10-02 05:38 UTC, MrScotch679 requested changes

2024-10-02 05:38 UTC, MrScotch679 commented on src/ui/components/table/table-columns/overall/my-requests-columns/my-requests-columns.jsx
> +      columnKey: columnnsKeys.shared.OBJECT,
columnnsKeys.shared.OBJECT_VALUE,

2024-10-02 06:01 UTC, MrScotch679 approved these changes

2024-10-02 06:01 UTC, merged