10830-refactor(warehouseModel):refactor model to ts
Asdevtest/amazon-frontend pull request #841
Opened 2024-10-11 11:49 UTC by tamashi22

не стал сильно типизироать, если где увидите оставьте коммент с типом на исправление

2024-10-11 14:16 UTC, oltree commented
посмотрел половину

2024-10-14 05:56 UTC, MrScotch679 requested changes

2024-10-14 05:56 UTC, MrScotch679 commented on src/ui/views/warehouse/warehouse-my-warehouse-view/warehouse-my-warehouse-view.jsx
>    }, [])
Удалить

2024-10-14 05:56 UTC, MrScotch679 commented on src/ui/views/warehouse/warehouse-my-warehouse-view/warehouse-my-warehouse-view.jsx
>          }
Отдельная функция

2024-10-14 05:56 UTC, MrScotch679 commented on src/ui/views/warehouse/warehouse-my-warehouse-view/warehouse-my-warehouse-view.jsx
> -import { toJS } from 'mobx'
Файл jsx, переписать на tsx

2024-10-14 05:56 UTC, MrScotch679 commented on src/ui/views/warehouse/warehouse-my-warehouse-view/warehouse-my-warehouse-view.constants.ts
>    'clientComment',
Удалить переменную filtersFields

2024-10-14 05:56 UTC, MrScotch679 commented on src/ui/views/warehouse/warehouse-my-warehouse-view/warehouse-my-warehouse-view.model.ts
> +    makeObservable(this, observerConfig)
Тут вызывать this.getTableSettingsPreset()

2024-10-14 05:56 UTC, MrScotch679 commented on src/ui/views/warehouse/warehouse-my-warehouse-view/warehouse-my-warehouse-view.jsx
>          onPaginationModelChange={viewModel.onPaginationModelChange}
Выше в toolbar должно быть
tablePresets: {
              showPresetsSelect: viewModel.showPresetsSelect,
              presetsTableData: viewModel.presetsTableData,
              handleChangeSelectState: viewModel.onChangeShowPresetsSelect,
              handleSetPresetActive: viewModel.handleSetPresetActive,
              handleCreateTableSettingsPreset: viewModel.handleCreateTableSettingsPreset,
              handleDeleteTableSettingsPreset: viewModel.handleDeleteTableSettingsPreset,
              handleUpdateTableSettingsPreset: viewModel.handleUpdateTableSettingsPreset,
              onClickAddQuickAccess: viewModel.onClickAddQuickAccess,
              onClickSaveRenamedPreset: viewModel.onClickSaveRenamedPreset,
            },

            resetFiltersBtnSettings: {
              onClickResetFilters: viewModel.onClickResetFilters,
              isSomeFilterOn: viewModel.isSomeFilterOn,
            },

            columsBtnSettings: {
              columnsModel: viewModel.columnsModel,
              columnVisibilityModel: viewModel.columnVisibilityModel,
              onColumnVisibilityModelChange: viewModel.onColumnVisibilityModelChange,
            },

            sortSettings: {
              sortModel: viewModel.sortModel,
              columnsModel: viewModel.columnsModel,
              onSortModelChange: viewModel.onChangeSortingModel,
            },

            tagSearchSettings: {
              tagList: viewModel.columnMenuSettings?.tags?.filterData,
              activeTags: viewModel.columnMenuSettings?.tags?.currentFilterData,
              isLoading: viewModel.columnMenuSettings?.filterRequestStatus === loadingStatus.IS_LOADING,
              getTags: () => viewModel.columnMenuSettings?.onClickFilterBtn(TAGS, DataGridFilterTables.PRODUCTS),
              setActiveProductsTag: viewModel.setActiveProductsTag,
            },

2024-10-14 05:56 UTC, MrScotch679 commented on src/ui/views/warehouse/warehouse-my-warehouse-view/warehouse-my-warehouse-view.model.ts
> +      fieldsForSearch: ['asin', 'amazonTitle', 'skuByClient', 'item', 'orderXid', 'xid', 'prepId'],
В переменную в отдельный файл

2024-10-14 05:56 UTC, MrScotch679 commented on src/ui/views/warehouse/warehouse-my-warehouse-view/warehouse-my-warehouse-view.model.ts
> +      filtersFields,
Заменить на filtersFields, найди строку ниже, как там сделано
const filtersFields = getFilterFields(columnsModel, additionalFields)

2024-10-14 06:03 UTC, oltree approved these changes

2024-10-15 05:38 UTC, merged