11010-fix(editBoxModal): fix checkboxes
Asdevtest/amazon-frontend pull request #883
Opened 2024-10-18 11:49 UTC by tamashi22

2024-10-18 13:11 UTC, oltree approved these changes

2024-10-21 05:38 UTC, MrScotch679 requested changes

2024-10-21 05:38 UTC, MrScotch679 commented on src/ui/components/forms/edit-box-storekeeper-form/edit-box-storekeeper-form.jsx
> +                                  disabled={!item.tmpBarCode.length && !item.barCode}
Юзается второй раз, в переменную

2024-10-21 05:38 UTC, MrScotch679 commented on src/ui/components/forms/edit-box-storekeeper-form/edit-box-storekeeper-form.jsx
> +                                  disabled={!item.tmpTransparencyFile.length && !item.transparencyFile}
Юзается второй раз, в переменную

2024-10-21 14:04 UTC, oltree approved these changes

2024-10-21 14:05 UTC, oltree approved these changes

2024-10-22 05:38 UTC, MrScotch679 approved these changes

2024-10-22 05:38 UTC, merged